# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'BookClub_iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BookClub_iOS
  pod 'BetterSegmentedControl'
  pod 'CryptoSwift'
  pod 'FFPopup'
  pod 'Gifu'
  pod 'Kingfisher'
  pod 'Moya'
  pod 'Moya/RxSwift'
  pod 'Pageboy'
  pod 'Tabman'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxGesture'
  pod 'RxKeyboard'
  pod 'SideMenu'
  pod 'SnapKit'
  pod 'Then'
  pod 'ZLPhotoBrowser'

  target 'BookClub_iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BookClub_iOSUITests' do
    # Pods for testing
  end

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      end
    end
end
